### ISSUE TITLE
Add Primary UI

### ISSUE THREAD

**Issue by gavination** [gavination/TemplateX#1]
Template App will have 3 screens:

- [x] Screen 1 will have 2 buttons #2 
- [x] Button 1 goes ListView #5 
- [x] Button 2 goes to MapView #4
